"""
perception/nce_contract.py

Data contract for the Narrative Counterfactual Engine (NCE).

This module defines the EXACT shape of NCEHypothesis — the output type that
NCE (built in a future session) will produce and that SSE/RSEM consume.
No LLM calling logic exists here — only the validated dataclass and a
mock hypothesis generator for testing the NCE→SSE→RSEM pipeline end-to-end.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from perception.sse import TECHNIQUE_TABLE


@dataclass(frozen=True)
class NCEHypothesis:
    """
    A single attack hypothesis generated by the NCE.

    This is the load-bearing contract between NCE and SSE/RSEM:
    - technique_id must be a key in TECHNIQUE_TABLE
    - nce_confidence is the LLM's self-reported confidence in [0, 1]
    - supporting_evidence_refs contains field NAMES only (e.g.
      ["raw_log_line", "registry_key"]) — NEVER raw content.
      This is what keeps NCE's output from smuggling contaminated
      evidence text into SSE/RSEM's reasoning.  SSE operates on
      resolved identifiers; if raw evidence text leaked through here,
      an attacker could influence graph traversal via prompt injection.
    - missing_context_flags names contextual gaps the NCE identified
    """
    technique_id: str
    source_account: str
    source_host: str
    target_host: str
    nce_confidence: float
    # Field NAMES only — never raw content.  This prevents contaminated
    # evidence text from smuggling into SSE/RSEM's reasoning path.
    supporting_evidence_refs: list[str]
    missing_context_flags: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.technique_id not in TECHNIQUE_TABLE:
            raise ValueError(
                f"technique_id {self.technique_id!r} is not in TECHNIQUE_TABLE. "
                f"Valid IDs: {sorted(TECHNIQUE_TABLE.keys())}"
            )
        if not (0.0 <= self.nce_confidence <= 1.0):
            raise ValueError(
                f"nce_confidence must be in [0.0, 1.0], got {self.nce_confidence!r}"
            )


def generate_mock_hypotheses(
    account_id: str,
    source_host: str,
    target_host: str,
    technique_ids: list[str] | None = None,
) -> list[NCEHypothesis]:
    """
    Generate plausible NCEHypothesis objects WITHOUT calling any LLM.

    Exists purely so RSEM can be tested end-to-end this session without
    needing NCE's real implementation.

    Args:
        account_id:    The account to attribute hypotheses to.
        source_host:   Source host for all hypotheses.
        target_host:   Target host for all hypotheses.
        technique_ids: Specific techniques.  Defaults to T1078, T1550, T1562.

    Returns:
        List of validated NCEHypothesis objects.
    """
    if technique_ids is None:
        technique_ids = ["T1078", "T1550", "T1562"]

    # Spread confidence across techniques to simulate realistic LLM output
    confidences = [0.85, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]
    evidence_refs_pool = [
        ["raw_log_line", "event_timestamp"],
        ["registry_key", "process_name"],
        ["auth_log_ref", "source_ip"],
    ]

    hypotheses: list[NCEHypothesis] = []
    for i, tid in enumerate(technique_ids):
        hypotheses.append(NCEHypothesis(
            technique_id=tid,
            source_account=account_id,
            source_host=source_host,
            target_host=target_host,
            nce_confidence=confidences[i % len(confidences)],
            supporting_evidence_refs=list(
                evidence_refs_pool[i % len(evidence_refs_pool)]
            ),
            missing_context_flags=[],
        ))

    return hypotheses
